sudo: required
services:
    - docker

before_install:
    - docker build -t samiperalahti/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run samiperalahti/react-test npm test -- --coverage

after_success:
    - docker build -t samiperalahti/multi-client ./client
    - docker build -t samiperalahti/multi-nginx ./nginx
    - docker build -t samiperalahti/multi-server ./server
    - docker build -t samiperalahti/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take these images and push them to dockerhub
    - docker push samiperalahti/multi-clien
    - docker push samiperalahti/multi-nginx
    - docker push samiperalahti/multi-server
    - docker push samiperalahti/multi-worker
